### PR TITLE
Remove unnecessary usage of StringBulder

### PR DESCRIPTION
**Pull request by wallner**
Replace an unnecessary usage of `StringBuilder` with plain string
concatenation, which is way easier on the eye, the compiler will take
care of optimizing it.

### CODE REVIEW

**Comment by dacrome** [comment]
Thank you!

**Comment by tkrille** [comment]
Commit message: "StringBulder"?

**Comment by tkrille** [comment]
@wallner please remove the source branch. you've accidentally created it in the upstream repo.

**Comment by wallner** [comment]
Ups. Done.

**Pull request merged**
