### PR TITLE
Extend SCIM address by display name to be SCIM conform

### PR DESCRIPTION
**Pull request by dacrome**
Any SCIM multi-valued attribute must have a display name:
https://tools.ietf.org/html/rfc7643#section-2.4

Also include display name of multi-valued attributes
in unit tests.

### CODE REVIEW

**Comment by dacrome** [comment]
Sorry, currently it is not clear if the SCIM Address should have a `display` sub-attribute. But I asked the SCIM mailing list.

I'm curious that the Address constructor [has a display parameter](https://github.com/osiam/connector4java/blob/338d2efb421370023b256981d27c3f7e856d593f/src/main/java/org/osiam/resources/scim/Address.java#L58).

All other SCIM mulit-valued attributes have the display sub-attribute, but currently they are mutable but [the SCIM spec says that the display have to be immutable](https://tools.ietf.org/html/rfc7643#section-2.4). So I think we need to fix this.

**Comment by tkrille** [comment]
This will be done after OSIAM 3.0

**Comment by tkrille** [comment]
Ignore my last comment.

**Comment by tkrille** [comment]
@dacrome:

> I'm curious that the Address constructor has a display parameter.

That's because we use inheritance incorrectly. I think we should refactor this with 2.0.

> All other SCIM mulit-valued attributes have the display sub-attribute, but currently they are mutable but the SCIM spec says that display has to be immutable. So I think we need to fix this.

It turns out, that the spec defines it inconsistently as `immutable`, `readOnly` and `readWrite`. Particularly, It does not define the attribute for `addresses`. Nevertheless, we've decided to add this attribute to `addresses` and also to give the service consumer full control over this field, making it have a `mutability` of `readWrite`.

**Pull request merged**
