### PR TITLE
Update dependency to scim-schema to latest snapshot

### PR DESCRIPTION
**Pull request by wallner**
Update dependency after release

### CODE REVIEW

**Comment by tkrille** [comment]
We've discussed that some time ago and decided to only bump the versions to the latest snapshot if we actually work on the dependency.

**Comment by tkrille** [comment]
Ok, I see. There are pending changes for `scim-schema`. Never mind ... :)

**Comment by tkrille** [comment]
But then we have to wait for the connector to be released today. This will happen within the next hours.

**Comment by wallner** [comment]
Thank you.

**Pull request merged**
